// MiniBlog API 定义，包含健康检查、用户管理和文章管理的 RPC 接口

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: apiserver/v1/apiserver.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MiniBog_Healthz_FullMethodName = "/v1.MiniBog/Healthz"
)

// MiniBogClient is the client API for MiniBog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MiniBlog 定义了一个 MiniBlog RPC 服务
type MiniBogClient interface {
	// Healthz 健康检查
	Healthz(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthzResponse, error)
}

type miniBogClient struct {
	cc grpc.ClientConnInterface
}

func NewMiniBogClient(cc grpc.ClientConnInterface) MiniBogClient {
	return &miniBogClient{cc}
}

func (c *miniBogClient) Healthz(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthzResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthzResponse)
	err := c.cc.Invoke(ctx, MiniBog_Healthz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MiniBogServer is the server API for MiniBog service.
// All implementations must embed UnimplementedMiniBogServer
// for forward compatibility.
//
// MiniBlog 定义了一个 MiniBlog RPC 服务
type MiniBogServer interface {
	// Healthz 健康检查
	Healthz(context.Context, *emptypb.Empty) (*HealthzResponse, error)
	mustEmbedUnimplementedMiniBogServer()
}

// UnimplementedMiniBogServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMiniBogServer struct{}

func (UnimplementedMiniBogServer) Healthz(context.Context, *emptypb.Empty) (*HealthzResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Healthz not implemented")
}
func (UnimplementedMiniBogServer) mustEmbedUnimplementedMiniBogServer() {}
func (UnimplementedMiniBogServer) testEmbeddedByValue()                 {}

// UnsafeMiniBogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MiniBogServer will
// result in compilation errors.
type UnsafeMiniBogServer interface {
	mustEmbedUnimplementedMiniBogServer()
}

func RegisterMiniBogServer(s grpc.ServiceRegistrar, srv MiniBogServer) {
	// If the following call pancis, it indicates UnimplementedMiniBogServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MiniBog_ServiceDesc, srv)
}

func _MiniBog_Healthz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiniBogServer).Healthz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiniBog_Healthz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiniBogServer).Healthz(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// MiniBog_ServiceDesc is the grpc.ServiceDesc for MiniBog service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MiniBog_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.MiniBog",
	HandlerType: (*MiniBogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Healthz",
			Handler:    _MiniBog_Healthz_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apiserver/v1/apiserver.proto",
}
